import { useState, useRef, useCallback, useEffect } from "react";

/* ═══════════════════════════════════════════════════════════════════════════
   BLOOB HAUS — Scene Nav Builder (Magic Machine)
   
   Outputs:
   1. ```scene-nav``` code fence (YAML) for markdown files
   2. Standalone HTML/CSS/JS embed code (= what the visualizer renders)
   
   The code fence is the source of truth.
   The embed code is the visualizer's rendered output, portable anywhere.
   ═══════════════════════════════════════════════════════════════════════════ */

const GLOW_PRESETS = [
  { name: "Gold",    color: "#FFD700" },
  { name: "Rose",    color: "#FF6B9D" },
  { name: "Cyan",    color: "#00E5FF" },
  { name: "Violet",  color: "#B388FF" },
  { name: "Mint",    color: "#69F0AE" },
  { name: "Coral",   color: "#FF8A65" },
  { name: "White",   color: "#FFFFFF" },
  { name: "Blue",    color: "#448AFF" },
];

const ACTION_TYPES = [
  { value: "filter", label: "Filter (Shopify tag)", icon: "◉" },
  { value: "link",   label: "Open link (new tab)",  icon: "↗" },
  { value: "anchor", label: "Jump to section",      icon: "↓" },
];

// ── Generate ```scene-nav``` YAML for markdown ────────────────────────────
function generateCodeFence(scene) {
  let yaml = "";
  if (scene.background) yaml += `background: ${scene.backgroundName || "background.png"}\n`;
  if (scene.elements.length === 0) return "```scene-nav\n" + yaml + "```";
  
  yaml += "elements:\n";
  scene.elements.forEach(el => {
    yaml += `  - image: ${el.fileName}\n`;
    yaml += `    x: ${Math.round(el.x * 10) / 10}\n`;
    yaml += `    y: ${Math.round(el.y * 10) / 10}\n`;
    yaml += `    scale: ${Math.round(el.scale * 10) / 10}\n`;
    if (el.label) yaml += `    label: "${el.label}"\n`;
    yaml += `    glow: "${el.glowColor}"\n`;
    if (el.glowIntensity !== 1) yaml += `    glowIntensity: ${el.glowIntensity}\n`;
    yaml += `    action: ${el.actionType}\n`;
    if (el.actionValue) yaml += `    value: "${el.actionValue}"\n`;
  });

  return "```scene-nav\n" + yaml + "```";
}

// ── Generate standalone embed HTML/CSS/JS ─────────────────────────────────
function generateEmbed(scene) {
  const config = {
    elements: scene.elements.map(el => ({
      image: el.fileName,
      src: el.fileName,
      x: Math.round(el.x * 10) / 10,
      y: Math.round(el.y * 10) / 10,
      scale: Math.round(el.scale * 10) / 10,
      label: el.label || null,
      glow: el.glowColor,
      glowIntensity: el.glowIntensity,
      action: el.actionType,
      value: el.actionValue || null,
    })),
    background: scene.backgroundName || null,
    backgroundSrc: scene.backgroundName || null,
  };

  return `<!-- Scene Nav — generated by Bloob Haus builder -->
<!-- Replace filename src values with hosted image URLs before deploying -->
<div id="bloob-scene-nav" style="position:relative;max-width:900px;margin:0 auto;">
<style>
  #bloob-scene-nav { font-family: system-ui, sans-serif; }
  .sn-bg { width:100%; display:block; }
  .sn-el {
    position:absolute; cursor:pointer;
    transition: filter 0.35s ease, transform 0.25s ease;
  }
  .sn-el:hover { transform: scale(1.06); }
  .sn-el img { width:100%; height:auto; display:block; pointer-events:none; user-select:none; }
  .sn-label {
    position:absolute; bottom:-26px; left:50%; transform:translateX(-50%);
    background:rgba(0,0,0,0.8); color:#fff; padding:3px 11px; border-radius:12px;
    font-size:12px; white-space:nowrap; opacity:0; transition:opacity 0.25s;
    pointer-events:none; letter-spacing:0.02em;
  }
  .sn-el:hover .sn-label { opacity:1; }
</style>
<script>
(function(){
  var S = ${JSON.stringify(config, null, 2)};
  var c = document.getElementById('bloob-scene-nav');
  if (S.backgroundSrc) {
    var bg = document.createElement('img');
    bg.className = 'sn-bg'; bg.src = S.backgroundSrc; bg.draggable = false;
    c.appendChild(bg);
  }
  S.elements.forEach(function(el) {
    var d = document.createElement('div');
    d.className = 'sn-el';
    d.style.left = el.x + '%';
    d.style.top = el.y + '%';
    d.style.width = el.scale + '%';
    var gI = el.glowIntensity || 1;
    var g1 = Math.round(8 * gI), g2 = Math.round(20 * gI), g3 = Math.round(40 * gI);
    d.onmouseenter = function() {
      d.style.filter = 'drop-shadow(0 0 '+g1+'px '+el.glow+') drop-shadow(0 0 '+g2+'px '+el.glow+') drop-shadow(0 0 '+g3+'px '+el.glow+'80)';
    };
    d.onmouseleave = function() { d.style.filter = 'none'; };
    d.onclick = function() {
      if (el.action === 'link' && el.value) window.open(el.value, '_blank');
      if (el.action === 'anchor' && el.value) {
        var t = document.getElementById(el.value) || document.querySelector('[name="'+el.value+'"]');
        if (t) t.scrollIntoView({ behavior:'smooth' });
      }
      if (el.action === 'filter' && el.value) {
        window.dispatchEvent(new CustomEvent('bloob:filter', { detail: { tag: el.value } }));
        var p = window.location.pathname;
        if (p.indexOf('/collections/') > -1) {
          window.location.href = p.split('?')[0] + '?filter.p.tag=' + encodeURIComponent(el.value);
        }
      }
    };
    var img = document.createElement('img');
    img.src = el.src; img.alt = el.label || ''; img.draggable = false;
    d.appendChild(img);
    if (el.label) {
      var lbl = document.createElement('span');
      lbl.className = 'sn-label'; lbl.textContent = el.label;
      d.appendChild(lbl);
    }
    c.appendChild(d);
  });
})();
</script>
</div>`;
}


// ── Draggable scene element ───────────────────────────────────────────────
function SceneElement({ el, selected, preview, onSelect, onMove, containerRef }) {
  const [hovered, setHovered] = useState(false);
  const [dragging, setDragging] = useState(false);
  const start = useRef({ mx: 0, my: 0, ex: 0, ey: 0 });

  const onDown = useCallback((e) => {
    if (preview) return;
    e.preventDefault();
    e.stopPropagation();
    onSelect(el.id);
    setDragging(true);
    const rect = containerRef.current.getBoundingClientRect();
    start.current = { mx: e.clientX, my: e.clientY, ex: el.x, ey: el.y, rw: rect.width, rh: rect.height };
    const move = (ev) => {
      const dx = ((ev.clientX - start.current.mx) / start.current.rw) * 100;
      const dy = ((ev.clientY - start.current.my) / start.current.rh) * 100;
      onMove(el.id, start.current.ex + dx, start.current.ey + dy);
    };
    const up = () => { setDragging(false); window.removeEventListener("mousemove", move); window.removeEventListener("mouseup", up); };
    window.addEventListener("mousemove", move);
    window.addEventListener("mouseup", up);
  }, [el, preview, onSelect, onMove, containerRef]);

  const gI = el.glowIntensity || 1;
  const glowFilter = `drop-shadow(0 0 ${8*gI}px ${el.glowColor}) drop-shadow(0 0 ${20*gI}px ${el.glowColor}) drop-shadow(0 0 ${40*gI}px ${el.glowColor}80)`;

  return (
    <div
      onMouseDown={onDown}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onClick={() => {
        if (preview && el.actionType === "link" && el.actionValue) window.open(el.actionValue, "_blank");
        if (preview && el.actionType === "anchor" && el.actionValue) {
          const t = document.getElementById(el.actionValue);
          if (t) t.scrollIntoView({ behavior: "smooth" });
        }
        if (preview && el.actionType === "filter") alert(`Filter → ${el.actionValue || "(no tag set)"}`);
      }}
      style={{
        position: "absolute",
        left: `${el.x}%`,
        top: `${el.y}%`,
        width: `${el.scale}%`,
        cursor: preview ? "pointer" : dragging ? "grabbing" : "grab",
        filter: hovered ? glowFilter : "none",
        transition: dragging ? "none" : "filter 0.35s ease, transform 0.25s ease",
        transform: hovered ? "scale(1.06)" : "scale(1)",
        zIndex: dragging ? 100 : selected ? 50 : 10,
        outline: !preview && selected ? `2px dashed ${el.glowColor}` : "none",
        outlineOffset: "4px",
      }}
    >
      <img src={el.src} alt={el.label || ""} draggable={false}
        style={{ width: "100%", height: "auto", display: "block", pointerEvents: "none", userSelect: "none" }} />
      {el.label && hovered && (
        <div style={{
          position: "absolute", bottom: "-28px", left: "50%", transform: "translateX(-50%)",
          background: "rgba(0,0,0,0.82)", color: "#fff", padding: "4px 12px", borderRadius: "14px",
          fontSize: "12px", whiteSpace: "nowrap", pointerEvents: "none",
          fontFamily: "'DM Sans', sans-serif", boxShadow: `0 0 12px ${el.glowColor}40`,
        }}>
          {el.label}
        </div>
      )}
    </div>
  );
}

// ── Inline text input ─────────────────────────────────────────────────────
function Field({ label, value, onChange, placeholder, mono }) {
  return (
    <div style={{ marginBottom: "10px" }}>
      <div style={{ fontSize: "10px", color: "#556", marginBottom: "3px", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: "0.08em" }}>{label}</div>
      <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}
        style={{
          width: "100%", padding: "7px 10px", borderRadius: "6px",
          border: "1px solid #1e1e30", background: "#0c0c18", color: "#ccc",
          fontSize: "13px", fontFamily: mono ? "'Space Mono', monospace" : "'DM Sans', sans-serif",
          outline: "none", boxSizing: "border-box", transition: "border-color 0.15s",
        }}
        onFocus={e => e.target.style.borderColor = "#444"}
        onBlur={e => e.target.style.borderColor = "#1e1e30"}
      />
    </div>
  );
}


// ═══════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════
export default function SceneBuilder() {
  const [elements, setElements] = useState([]);
  const [background, setBackground] = useState(null);
  const [backgroundName, setBackgroundName] = useState("");
  const [selectedId, setSelectedId] = useState(null);
  const [mode, setMode] = useState("edit"); // edit | preview | code
  const [codeTab, setCodeTab] = useState("embed"); // embed | markdown
  const containerRef = useRef(null);
  const bgRef = useRef(null);
  const elRef = useRef(null);

  const sel = elements.find(e => e.id === selectedId);

  const update = (id, patch) => setElements(p => p.map(e => e.id === id ? { ...e, ...patch } : e));
  const remove = (id) => { setElements(p => p.filter(e => e.id !== id)); if (selectedId === id) setSelectedId(null); };

  const handleBg = (e) => {
    const f = e.target.files[0]; if (!f) return;
    setBackgroundName(f.name);
    const r = new FileReader();
    r.onload = ev => setBackground(ev.target.result);
    r.readAsDataURL(f);
  };

  const handleEls = (e) => {
    Array.from(e.target.files).forEach((f, i) => {
      const r = new FileReader();
      r.onload = ev => {
        const img = new Image();
        img.onload = () => {
          setElements(prev => [...prev, {
            id: `el_${Date.now()}_${i}`,
            src: ev.target.result,
            fileName: f.name,
            naturalW: img.naturalWidth,
            naturalH: img.naturalHeight,
            x: 15 + Math.random() * 25,
            y: 15 + Math.random() * 25,
            scale: 18,
            label: f.name.replace(/\.[^.]+$/, ""),
            glowColor: GLOW_PRESETS[(prev.length + i) % GLOW_PRESETS.length].color,
            glowIntensity: 1,
            actionType: "filter",
            actionValue: "",
          }]);
        };
        img.src = ev.target.result;
      };
      r.readAsDataURL(f);
    });
    e.target.value = "";
  };

  // Keyboard
  useEffect(() => {
    const h = (e) => {
      if ((e.key === "Delete" || e.key === "Backspace") && selectedId && !["INPUT","TEXTAREA"].includes(e.target.tagName)) remove(selectedId);
      if (e.key === "Escape") { setSelectedId(null); }
    };
    window.addEventListener("keydown", h);
    return () => window.removeEventListener("keydown", h);
  }, [selectedId]);

  const scene = { elements, background, backgroundName };
  const fenceCode = generateCodeFence(scene);
  const embedCode = generateEmbed(scene);

  const tabBtn = (active) => ({
    padding: "6px 14px", borderRadius: "6px", border: `1px solid ${active ? "#FFD700" : "#1e1e30"}`,
    background: active ? "#FFD70012" : "transparent", color: active ? "#FFD700" : "#556",
    cursor: "pointer", fontSize: "12px", fontFamily: "'Space Mono', monospace", fontWeight: active ? 600 : 400,
    transition: "all 0.15s",
  });

  return (
    <div style={{ minHeight: "100vh", background: "#08080e", color: "#ddd", fontFamily: "'DM Sans', system-ui, sans-serif", display: "flex", flexDirection: "column" }}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet" />
      <input ref={bgRef} type="file" accept="image/png,image/svg+xml,image/webp" onChange={handleBg} style={{ display: "none" }} />
      <input ref={elRef} type="file" accept="image/png,image/svg+xml,image/webp" multiple onChange={handleEls} style={{ display: "none" }} />

      {/* ── Top bar ──────────────────────────────────────────── */}
      <div style={{ padding: "12px 20px", borderBottom: "1px solid #141422", display: "flex", alignItems: "center", justifyContent: "space-between", background: "#0a0a14", flexWrap: "wrap", gap: "10px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <div style={{ width: "28px", height: "28px", borderRadius: "8px", background: "linear-gradient(135deg, #FFD700, #FF6B9D)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: 700 }}>✦</div>
          <div>
            <span style={{ fontWeight: 700, fontSize: "14px", letterSpacing: "-0.02em" }}>Scene Nav</span>
            <span style={{ fontSize: "11px", color: "#445", fontFamily: "'Space Mono', monospace", marginLeft: "8px" }}>magic machine</span>
          </div>
        </div>
        <div style={{ display: "flex", gap: "4px", background: "#0c0c16", borderRadius: "8px", padding: "3px", border: "1px solid #141422" }}>
          {[["edit","Edit"],["preview","Preview"],["code","Code"]].map(([m, label]) => (
            <button key={m} onClick={() => setMode(m)} style={{
              padding: "6px 16px", borderRadius: "6px", border: "none",
              background: mode === m ? "#1a1a2e" : "transparent",
              color: mode === m ? "#FFD700" : "#556", cursor: "pointer",
              fontSize: "12px", fontFamily: "'Space Mono', monospace", fontWeight: mode === m ? 700 : 400,
              transition: "all 0.15s",
            }}>{label}</button>
          ))}
        </div>
      </div>

      <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>

        {/* ── Left panel (edit mode) ─────────────────────────── */}
        {mode === "edit" && (
          <div style={{ width: "260px", borderRight: "1px solid #141422", background: "#0a0a14", padding: "14px", overflowY: "auto", flexShrink: 0 }}>

            <div style={{ marginBottom: "16px", display: "flex", flexDirection: "column", gap: "6px" }}>
              <button onClick={() => bgRef.current.click()} style={{
                width: "100%", padding: "9px", borderRadius: "7px", border: "1px dashed #1e1e30",
                background: "transparent", color: "#556", cursor: "pointer", fontSize: "12px",
                fontFamily: "'DM Sans', sans-serif", transition: "all 0.15s",
              }}
                onMouseEnter={e => { e.target.style.borderColor = "#FFD700"; e.target.style.color = "#FFD700"; }}
                onMouseLeave={e => { e.target.style.borderColor = "#1e1e30"; e.target.style.color = "#556"; }}
              >{background ? "↻ Replace background" : "＋ Background PNG"}</button>
              <button onClick={() => elRef.current.click()} style={{
                width: "100%", padding: "9px", borderRadius: "7px", border: "1px dashed #1e1e30",
                background: "transparent", color: "#556", cursor: "pointer", fontSize: "12px",
                fontFamily: "'DM Sans', sans-serif", transition: "all 0.15s",
              }}
                onMouseEnter={e => { e.target.style.borderColor = "#69F0AE"; e.target.style.color = "#69F0AE"; }}
                onMouseLeave={e => { e.target.style.borderColor = "#1e1e30"; e.target.style.color = "#556"; }}
              >＋ Add element PNGs</button>
            </div>

            <div style={{ fontSize: "10px", color: "#445", fontFamily: "'Space Mono', monospace", marginBottom: "6px", textTransform: "uppercase", letterSpacing: "0.1em" }}>
              Elements · {elements.length}
            </div>
            {elements.map(el => (
              <div key={el.id} onClick={() => setSelectedId(el.id)} style={{
                padding: "8px 10px", marginBottom: "3px", borderRadius: "7px",
                background: selectedId === el.id ? "#111122" : "transparent",
                border: `1px solid ${selectedId === el.id ? el.glowColor + "30" : "transparent"}`,
                cursor: "pointer", display: "flex", alignItems: "center", gap: "8px", transition: "all 0.12s",
              }}>
                <div style={{ width: "26px", height: "26px", borderRadius: "5px", background: "#0c0c16", overflow: "hidden", flexShrink: 0, border: `1px solid ${el.glowColor}20`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                  <img src={el.src} style={{ maxWidth: "100%", maxHeight: "100%", objectFit: "contain" }} />
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: "12px", fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{el.label || el.fileName}</div>
                  <div style={{ fontSize: "10px", color: "#445", fontFamily: "'Space Mono', monospace" }}>
                    {el.actionType === "filter" && el.actionValue ? `◉ ${el.actionValue}` : el.actionType === "link" ? "↗ link" : el.actionType === "anchor" ? "↓ anchor" : "◉ filter"}
                  </div>
                </div>
                <div style={{ width: "10px", height: "10px", borderRadius: "50%", background: el.glowColor, flexShrink: 0, boxShadow: `0 0 6px ${el.glowColor}60` }} />
              </div>
            ))}

            {elements.length === 0 && (
              <div style={{ textAlign: "center", padding: "24px 8px", color: "#333", fontSize: "12px", lineHeight: 1.7 }}>
                Upload a background,<br />then add character PNGs<br />to build your scene.
              </div>
            )}

            {/* ── Selected element properties ──────────────────── */}
            {sel && (
              <div style={{ marginTop: "16px", padding: "12px", borderRadius: "8px", background: "#0c0c18", border: `1px solid ${sel.glowColor}15` }}>
                <div style={{ fontSize: "10px", color: "#445", fontFamily: "'Space Mono', monospace", marginBottom: "10px", textTransform: "uppercase", letterSpacing: "0.08em" }}>Properties</div>

                <Field label="Label" value={sel.label} onChange={v => update(sel.id, { label: v })} placeholder="Display name" />

                {/* Scale (aspect-ratio locked — width only, height follows naturally) */}
                <div style={{ marginBottom: "10px" }}>
                  <div style={{ fontSize: "10px", color: "#556", marginBottom: "4px", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: "0.08em" }}>
                    Size · {Math.round(sel.scale)}%
                  </div>
                  <input type="range" min={3} max={60} step={0.5} value={sel.scale}
                    onChange={e => update(sel.id, { scale: Number(e.target.value) })}
                    style={{ width: "100%", accentColor: sel.glowColor }} />
                </div>

                {/* Glow color */}
                <div style={{ marginBottom: "10px" }}>
                  <div style={{ fontSize: "10px", color: "#556", marginBottom: "5px", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: "0.08em" }}>Glow color</div>
                  <div style={{ display: "flex", gap: "5px", flexWrap: "wrap" }}>
                    {GLOW_PRESETS.map(p => (
                      <div key={p.color} onClick={() => update(sel.id, { glowColor: p.color })}
                        title={p.name}
                        style={{
                          width: "20px", height: "20px", borderRadius: "5px", background: p.color, cursor: "pointer",
                          border: sel.glowColor === p.color ? "2px solid #fff" : "2px solid transparent",
                          boxShadow: sel.glowColor === p.color ? `0 0 8px ${p.color}` : "none",
                          transition: "all 0.12s",
                        }} />
                    ))}
                  </div>
                </div>

                {/* Glow intensity */}
                <div style={{ marginBottom: "12px" }}>
                  <div style={{ fontSize: "10px", color: "#556", marginBottom: "4px", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: "0.08em" }}>
                    Glow intensity · {sel.glowIntensity.toFixed(1)}x
                  </div>
                  <input type="range" min={0.2} max={3} step={0.1} value={sel.glowIntensity}
                    onChange={e => update(sel.id, { glowIntensity: Number(e.target.value) })}
                    style={{ width: "100%", accentColor: sel.glowColor }} />
                </div>

                {/* Action type */}
                <div style={{ marginBottom: "10px" }}>
                  <div style={{ fontSize: "10px", color: "#556", marginBottom: "5px", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: "0.08em" }}>Click action</div>
                  <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
                    {ACTION_TYPES.map(a => (
                      <div key={a.value} onClick={() => update(sel.id, { actionType: a.value })}
                        style={{
                          padding: "6px 10px", borderRadius: "6px", cursor: "pointer",
                          background: sel.actionType === a.value ? `${sel.glowColor}12` : "transparent",
                          border: `1px solid ${sel.actionType === a.value ? sel.glowColor + "40" : "#1a1a2e"}`,
                          color: sel.actionType === a.value ? sel.glowColor : "#667",
                          fontSize: "12px", transition: "all 0.12s",
                          display: "flex", alignItems: "center", gap: "6px",
                        }}>
                        <span style={{ fontFamily: "'Space Mono', monospace" }}>{a.icon}</span> {a.label}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Action value */}
                <Field
                  label={sel.actionType === "filter" ? "Shopify tag" : sel.actionType === "link" ? "URL" : "Heading ID / anchor"}
                  value={sel.actionValue}
                  onChange={v => update(sel.id, { actionValue: v })}
                  placeholder={sel.actionType === "filter" ? "character:bloob" : sel.actionType === "link" ? "https://..." : "section-name"}
                  mono
                />

                <button onClick={() => remove(sel.id)} style={{
                  width: "100%", padding: "7px", borderRadius: "6px", border: "1px solid #552222",
                  background: "transparent", color: "#aa4444", cursor: "pointer", fontSize: "11px",
                  fontFamily: "'DM Sans', sans-serif", transition: "all 0.15s", marginTop: "4px",
                }}
                  onMouseEnter={e => e.target.style.background = "#221111"}
                  onMouseLeave={e => e.target.style.background = "transparent"}
                >Remove</button>
              </div>
            )}
          </div>
        )}

        {/* ── Canvas ─────────────────────────────────────────── */}
        {mode !== "code" && (
          <div style={{
            flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
            padding: "24px", overflow: "auto",
            background: mode === "preview" ? "radial-gradient(ellipse at center, #0e0e1a 0%, #050508 100%)" : "#08080e",
          }}>
            <div ref={containerRef}
              onClick={e => { if (e.target === e.currentTarget) setSelectedId(null); }}
              style={{
                position: "relative", width: "100%", maxWidth: "800px",
                aspectRatio: background ? undefined : "16/10",
                minHeight: background ? undefined : "380px",
                borderRadius: "10px", overflow: "hidden",
                border: mode === "preview" ? "none" : "1px solid #141422",
                background: background ? "transparent" : mode === "preview" ? "transparent"
                  : "repeating-conic-gradient(#111118 0% 25%, #0d0d14 0% 50%) 50% / 18px 18px",
              }}>
              {background && <img src={background} style={{ width: "100%", display: "block", pointerEvents: "none", userSelect: "none" }} draggable={false} />}
              {elements.map(el => (
                <SceneElement key={el.id} el={el} selected={selectedId === el.id} preview={mode === "preview"}
                  onSelect={setSelectedId}
                  onMove={(id, x, y) => update(id, { x, y })}
                  containerRef={containerRef} />
              ))}
              {!background && elements.length === 0 && (
                <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: "#222", gap: "10px" }}>
                  <div style={{ fontSize: "42px", opacity: 0.4 }}>✦</div>
                  <div style={{ fontSize: "13px", textAlign: "center", lineHeight: 1.7, maxWidth: "240px" }}>
                    Upload a transparent background PNG, then add character images to position them.
                  </div>
                </div>
              )}
            </div>
            {mode === "preview" && elements.length > 0 && (
              <div style={{ marginTop: "14px", fontSize: "11px", color: "#334", fontFamily: "'Space Mono', monospace", textAlign: "center" }}>
                hover to glow · click to activate
              </div>
            )}
          </div>
        )}

        {/* ── Code panel ─────────────────────────────────────── */}
        {mode === "code" && (
          <div style={{ flex: 1, display: "flex", flexDirection: "column", background: "#0a0a14" }}>
            <div style={{ padding: "12px 16px", borderBottom: "1px solid #141422", display: "flex", gap: "6px", flexWrap: "wrap" }}>
              {[["embed", "Embed HTML"], ["markdown", "``` Markdown ```"]].map(([t, label]) => (
                <button key={t} onClick={() => setCodeTab(t)} style={tabBtn(codeTab === t)}>{label}</button>
              ))}
            </div>

            <div style={{ padding: "12px 16px", borderBottom: "1px solid #0e0e1e", fontSize: "12px", color: "#445", lineHeight: 1.6 }}>
              {codeTab === "markdown" ? (
                <>The <span style={{ color: "#FFD700", fontFamily: "'Space Mono', monospace" }}>```scene-nav```</span> code fence for your markdown file. This is the source of truth — the visualizer reads this config and renders the interactive scene at build time.</>
              ) : (
                <>Standalone HTML/CSS/JS — paste into Shopify (custom section or page HTML), any website, or embed anywhere. For production, replace data-URI image sources with hosted URLs.</>
              )}
            </div>

            <div style={{ flex: 1, overflow: "auto", padding: "16px" }}>
              <pre style={{
                margin: 0, fontSize: "11px", lineHeight: 1.65, color: "#778",
                fontFamily: "'Space Mono', monospace", whiteSpace: "pre-wrap", wordBreak: "break-all",
              }}>
                {elements.length > 0 ? (codeTab === "markdown" ? fenceCode : embedCode) : "// Add elements to generate code"}
              </pre>
            </div>

            <div style={{ padding: "12px 16px", borderTop: "1px solid #141422" }}>
              <button onClick={() => {
                const code = codeTab === "markdown" ? fenceCode : embedCode;
                navigator.clipboard?.writeText(code);
              }} style={{
                width: "100%", padding: "10px", borderRadius: "8px", border: "none",
                background: "linear-gradient(135deg, #FFD700, #FF6B9D)", color: "#000",
                fontWeight: 700, fontSize: "13px", cursor: "pointer", fontFamily: "'DM Sans', sans-serif",
              }}>
                Copy {codeTab === "markdown" ? "Markdown" : "Embed Code"}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
