import { readdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import taskLists from "markdown-it-task-lists";
import pluginRss from "@11ty/eleventy-plugin-rss";
import Image from "@11ty/eleventy-img";
import {
  loadSiteConfig,
  resolveSiteName,
} from "./scripts/utils/config-loader.js";

// Auto-discover visualizer packages from lib/visualizers/
async function loadVisualizers() {
  const dir = "lib/visualizers";
  if (!existsSync(dir)) return [];

  const folders = readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  const visualizers = [];
  for (const name of folders) {
    const indexPath = join(dir, name, "index.js");
    if (existsSync(indexPath)) {
      const mod = await import(`./${indexPath}`);
      visualizers.push({ name, ...mod });
    }
  }
  return visualizers;
}

export default async function (eleventyConfig) {
  // Load site configuration
  const siteName = resolveSiteName();
  const siteConfig = await loadSiteConfig(siteName);

  // Load visualizer modules for build-time transforms
  const visualizers = await loadVisualizers();
  // RSS feed plugin (provides dateToRfc3339, htmlToAbsoluteUrls, etc.)
  eleventyConfig.addPlugin(pluginRss);

  // Don't use .gitignore for Eleventy's ignore rules
  // (src/content/ is gitignored since it's generated, but Eleventy must process it)
  eleventyConfig.setUseGitIgnore(false);

  // Pass through static assets
  eleventyConfig.addPassthroughCopy("src/assets");
  // Media files (images from preprocessor) — serve at /media/
  eleventyConfig.addPassthroughCopy({ "src/media": "media" });
  // OG preview images — serve at /og/ (separate from /media/ to avoid optimization)
  eleventyConfig.addPassthroughCopy({ "src/og": "og" });
  // Graph data — always generated by preprocessor, served at /graph.json
  eleventyConfig.addPassthroughCopy({ "src/graph.json": "graph.json" });
  // Graph settings — vault defaults from .bloob/graph.yaml, served at /graph-settings.json
  eleventyConfig.addPassthroughCopy({
    "src/graph-settings.json": "graph-settings.json",
  });
  // Tag index — served at /tagIndex.json for the tags visualizer (runtime fetch)
  eleventyConfig.addPassthroughCopy({
    "src/_data/tagIndex.json": "tagIndex.json",
  });

  // Watch for changes during development
  eleventyConfig.addWatchTarget("src/assets/");
  eleventyConfig.addWatchTarget("lib/");

  // Don't watch media — large binary files synced by iCloud/Dropbox cause rebuild loops
  eleventyConfig.watchIgnores.add("src/media/**");
  eleventyConfig.watchIgnores.add("src/og/**");
  eleventyConfig.watchIgnores.add(".cache/**");

  // Enable task list checkboxes in markdown (- [ ] and - [x] syntax)
  eleventyConfig.amendLibrary("md", (mdLib) => {
    mdLib.use(taskLists, { enabled: false, label: true });
  });

  // Date formatting filter
  // Handles JS Date objects and YYYY-MM-DD strings.
  // YYYY-MM-DD strings are treated as local noon to avoid off-by-one timezone issues.
  eleventyConfig.addFilter("dateFormat", function (date) {
    if (!date) return "";
    let d;
    if (typeof date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(date.trim())) {
      d = new Date(date.trim() + "T12:00:00");
    } else {
      d = new Date(date);
    }
    return d.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  });

  // Truncate filter (Hugo has this built-in)
  eleventyConfig.addFilter("truncate", function (str, len) {
    if (!str) return "";
    if (str.length <= len) return str;
    return str.slice(0, len) + "…";
  });

  // Head filter — take first N items from array (like Hugo's `first`)
  eleventyConfig.addFilter("head", function (array, n) {
    if (!Array.isArray(array)) return [];
    return array.slice(0, n);
  });

  // Convert \n newlines to <br> — used for multi-line bylines
  eleventyConfig.addFilter("nl2br", function (str) {
    if (!str) return "";
    return String(str).replace(/\n/g, "<br>");
  });

  // Render markdown-style links [text](url) → <a href="url">text</a>
  // External URLs (https?://) open in a new tab; bare paths are treated as internal.
  eleventyConfig.addFilter("mdLinks", function (str) {
    if (!str) return "";
    return String(str).replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, text, url) => {
      const isExternal = /^https?:\/\//.test(url);
      const attrs = isExternal
        ? `href="${url}" target="_blank" rel="noopener"`
        : `href="${url}"`;
      return `<a ${attrs}>${text}</a>`;
    });
  });

  // Capitalize filter
  eleventyConfig.addFilter("capitalize", function (str) {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1);
  });

  // Title case filter — matches Hugo's .Title behavior (lowercase small words)
  // Also converts hyphens to spaces for slugified strings
  eleventyConfig.addFilter("titleCase", function (str) {
    if (!str) return "";
    const small = new Set([
      "a",
      "an",
      "and",
      "as",
      "at",
      "but",
      "by",
      "for",
      "in",
      "nor",
      "of",
      "on",
      "or",
      "so",
      "the",
      "to",
      "up",
    ]);
    return str
      .replace(/-/g, " ")
      .split(" ")
      .map((word, i) => {
        if (i > 0 && small.has(word.toLowerCase())) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1);
      })
      .join(" ");
  });

  // Filter out system/reserved tags from display
  function filterTagList(tags) {
    return (tags || []).filter(
      (tag) => !["all", "nav", "posts", "not-for-public"].includes(tag),
    );
  }
  eleventyConfig.addFilter("filterTagList", filterTagList);

  // Slugify filter for tag URLs
  eleventyConfig.addFilter("slugify", function (str) {
    if (!str) return "";
    return str
      .toLowerCase()
      .replace(/[^a-z0-9\s/-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  });

  // Collection of all unique tags (for tag page pagination)
  eleventyConfig.addCollection("tagList", function (collectionApi) {
    const tagSet = new Set();
    collectionApi.getAll().forEach((item) => {
      (item.data.tags || []).forEach((tag) => tagSet.add(tag));
    });
    return filterTagList([...tagSet]).sort();
  });

  // Auto-detect sections from content directory structure
  // Mirrors Hugo's .Site.Sections behavior
  // Excludes non-content directories (media, assets, tags, etc.)
  const RESERVED_DIRS = new Set(["media", "assets", "tags", "pagefind", "og", "search"]);

  eleventyConfig.addCollection("sections", function (collectionApi) {
    const sections = new Set();
    collectionApi.getAll().forEach((item) => {
      const parts = item.url.split("/").filter(Boolean);
      if (parts.length > 1 && !RESERVED_DIRS.has(parts[0])) {
        sections.add(parts[0]);
      }
    });
    return [...sections].sort();
  });

  // Dynamic per-section collections
  // Auto-discovers top-level content folders in src/ and registers a collection for each.
  // Each section gets its own top-level addCollection call (Eleventy doesn't support
  // registering collections inside another collection callback — they resolve too late).
  // Collection names are camelCased from folder slugs (e.g., "lists-of-favorites" → "listsOfFavorites").
  const srcDirs = readdirSync("src", { withFileTypes: true })
    .filter((d) => d.isDirectory() && !RESERVED_DIRS.has(d.name) && !d.name.startsWith("_"))
    .map((d) => d.name);

  for (const section of srcDirs) {
    const collectionName = section.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    eleventyConfig.addCollection(collectionName, function (collectionApi) {
      return collectionApi.getAll()
        .filter((item) => {
          const parts = item.url.split("/").filter(Boolean);
          return parts.length > 1 && parts[0] === section;
        })
        .sort((a, b) => (b.date || 0) - (a.date || 0));
    });
  }

  // Backlinks: compute which pages link to each other
  // Uses addCollection to attach backlinks data to each page.
  // Reads source files from disk (stable API, not Eleventy internals).
  if (siteConfig.features?.backlinks !== false)
    eleventyConfig.addCollection("withBacklinks", function (collectionApi) {
      const all = collectionApi.getAll();

      // Extract internal links from markdown source (exclude images)
      function extractLinks(source) {
        const links = [];
        // Markdown links [text](url) — exclude images ![alt](url)
        const mdLinks = source.matchAll(/(?<!!)\[([^\]]*)\]\(([^)]+)\)/g);
        for (const m of mdLinks) {
          const url = m[2];
          // Only internal links (starting with /)
          if (url.startsWith("/") && !url.startsWith("/media/")) {
            links.push(url.replace(/\/$/, "")); // normalize trailing slash
          }
        }
        return links;
      }

      // First pass: build a map of page URL → outgoing links
      const linkMap = new Map();
      for (const page of all) {
        if (!page.inputPath.endsWith(".md")) continue;
        try {
          const source = readFileSync(page.inputPath, "utf-8");
          linkMap.set(page.url.replace(/\/$/, ""), extractLinks(source));
        } catch {
          // File may not exist if it's a generated page
        }
      }

      // Second pass: for each page, find all pages that link TO it
      for (const page of all) {
        const pageUrl = page.url.replace(/\/$/, "");
        page.data.backlinks = all
          .filter((other) => {
            if (other.url === page.url) return false;
            const otherUrl = other.url.replace(/\/$/, "");
            const outgoing = linkMap.get(otherUrl);
            return outgoing?.includes(pageUrl);
          })
          .map((p) => ({ url: p.url, title: p.data.title }));
      }

      return all;
    });

  // Image optimization transform
  // Finds <img src="/media/..."> in rendered HTML, generates WebP + original
  // at reasonable sizes, replaces with <picture> element.
  // Only /media/ paths are optimized — everything in /media/ is user content
  // (including nested folders). OG images live at /og/ and are never touched.
  const mediaConfig = siteConfig.media || {};
  if (mediaConfig.optimize !== false)
    eleventyConfig.addTransform("optimizeImages", async function (content) {
      if (!this.page.outputPath?.endsWith(".html")) return content;

      const imgRegex = /<img\s+([^>]*?)src="(\/media\/[^"]+)"([^>]*?)>/gi;
      const matches = [...content.matchAll(imgRegex)];
      if (matches.length === 0) return content;

      let result = content;
      for (const match of matches) {
        const [originalTag, before, src, after] = match;
        const inputPath = join("src", decodeURIComponent(src));
        if (!existsSync(inputPath)) continue;

        // Extract alt text if present
        const altMatch = (before + after).match(/alt="([^"]*)"/);
        const alt = altMatch ? altMatch[1] : "";

        // Skip GIFs — serve untouched to preserve animation
        const ext = src.toLowerCase().split(".").pop();
        if (ext === "gif") continue;

        try {
          // WebP for modern browsers (alpha preserved), PNG fallback for old browsers.
          // No JPEG — JPEG has no alpha channel and would make transparency black.
          const formats = mediaConfig.formats || ["webp", "png"];

          const metadata = await Image(inputPath, {
            widths: mediaConfig.widths || [600, 1200],
            formats,
            outputDir: join(outputDir, "media/optimized"),
            urlPath: "/media/optimized/",
            filenameFormat: function (id, src, width, format) {
              const name = src.split("/").pop().split(".")[0];
              return `${name}-${width}w.${format}`;
            },
          });

          const pictureHtml = Image.generateHTML(metadata, {
            alt,
            sizes: "(max-width: 600px) 100vw, 800px",
            loading: "lazy",
            decoding: "async",
          });

          // Wrap in <a> for PhotoSwipe: dimensions from metadata, original path for full-res button
          const webpImages = metadata.webp || [];
          const allImages = webpImages.length > 0 ? webpImages : (metadata.png || []);
          const largest = allImages[allImages.length - 1];
          const pswpSrcset = webpImages.map((img) => `${img.url} ${img.width}w`).join(", ");

          const wrapped = [
            `<a class="pswp-gallery__item"`,
            ` href="${src}"`,
            ` data-pswp-src="${largest.url}"`,
            pswpSrcset ? ` data-pswp-srcset="${pswpSrcset}"` : "",
            ` data-pswp-width="${largest.width}"`,
            ` data-pswp-height="${largest.height}"`,
            ` data-original="${src}"`,
            `>`,
            pictureHtml,
            `</a>`,
          ].join("");

          result = result.replace(originalTag, wrapped);
        } catch (e) {
          // If image processing fails, keep original tag
          console.warn(`[image] Failed to optimize ${src}: ${e.message}`);
        }
      }
      return result;
    });

  // Visualizer build-time transform
  // Runs each visualizer's transform() on rendered HTML output.
  // Runtime-only visualizers (like checkbox-tracker) return content unchanged.
  // Build-time visualizers (future: timeline, recipe-card) modify HTML here.
  const buildTimeVisualizers = visualizers.filter(
    (v) => typeof v.transform === "function" && v.type !== "runtime",
  );

  if (buildTimeVisualizers.length > 0) {
    eleventyConfig.addTransform("visualizers", function (content) {
      if (!this.page.outputPath?.endsWith(".html")) return content;

      let result = content;
      for (const viz of buildTimeVisualizers) {
        result = viz.transform(result);
      }
      return result;
    });
  }

  // Determine output directory and path prefix based on mount_path
  // e.g., mount_path: "marbles" → output to _site/marbles/, URLs start with /marbles/
  const mountPath = siteConfig.mount_path;
  const outputDir = mountPath ? `_site/${mountPath}` : "_site";
  const pathPrefix = mountPath ? `/${mountPath}/` : "/";

  if (mountPath) {
    console.log(`[eleventy] Mount path: /${mountPath}/ → output to ${outputDir}`);
  }

  return {
    dir: {
      input: "src",
      includes: "_includes",
      data: "_data",
      output: outputDir,
    },
    pathPrefix,
    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
  };
}
